### ISSUE TITLE
NHMDJ-3.1

### ISSUE THREAD

**Issue by lewandowski-jan** [iasiu/nursing-home-manager#8]
#Subtasks
- [x] Delete ss in admin panel, provide plural names
- [x] Add str method to all models
- [x] Add test data to all tables
- [x] Check if we can automate fields like oblozenie in Pokoje based on number of assigned Seniorzy
- [x] Set Leki at Karta zdrowia to not mandatory
- [x] Review on_delete
- [x ] Add field choices where we had defined rules in db project
